#107: Самый быстрый кликкер
YaFriends/ya-game-frontend pull request #124
Opened 2021-12-24 13:57 UTC by venmovs

Closes #107

2021-12-26 10:15 UTC, Tenutes requested changes
Оооооооочень классно, каеф, пара моментов и прям течем в мастер.

2021-12-26 10:15 UTC, Tenutes commented on src/core/MiniGames/ClickMoreMiniGame.ts
> +    }, 1000);
го 1000 в константы

2021-12-26 10:15 UTC, Tenutes commented on src/core/MiniGames/ClickMoreMiniGame.ts
> +    let countDown = 3;
и 3 в константы тоже

2021-12-26 10:15 UTC, Tenutes commented on src/core/MiniGames/clickMoreMiniGame/Opponent.ts
> +    this.interval = window.setInterval(this._addPoint, 300);
добавь 300 в константы. Потом можно будет как-то манипулировать этим (увеличивая сложность)

2021-12-26 10:15 UTC, Tenutes commented on src/core/MiniGames/clickMoreMiniGame/Opponent.ts
> +    this.interval = 0;
] где-то это типизировал уже, а то мне чет не нравится интервал начальный с айдишником ноль)) И, ес честно, что setInterval не совсем number возвращает

2021-12-26 13:23 UTC, YurikEz approved these changes
Круто!

2022-01-02 13:59 UTC, Tenutes approved these changes

2022-01-10 11:21 UTC, spt30 commented on src/core/MiniGames/clickMoreMiniGame/Flask.ts
> +  leftSide: boolean;
костыль какой-то
а если на троих игру захочется сделать? будем 2 булеана писать?
надо переделать на enum

2022-01-18 05:55 UTC, venmovs commented on src/core/MiniGames/clickMoreMiniGame/Flask.ts
> +  leftSide: boolean;
поменял на enum

2022-01-18 21:03 UTC, spt30 approved these changes

2022-01-19 05:12 UTC, merged