Sprint 7 93
YaFriends/ya-game-frontend pull request #125
Opened 2021-12-28 14:28 UTC by venmovs

Есть ряд проблем, с которыми не могу побороться: 
1. В dist у меня не появляется файл со стилями
2. nodemon считывает изменения в файлах, но браузер сам не перезагружается после изменений
3. не могу подключить redux, хотя Рома написал, что он это сделает, я пытался но все безуспешно
4. вообще нету понимания то ли я делаю или нет :(

2021-12-28 14:30 UTC, Tenutes commented
1. Переименуй ПР => SSR

2021-12-28 14:36 UTC, Tenutes requested changes

2021-12-28 14:36 UTC, Tenutes commented on babel.config.js
> +        ['@babel/preset-env', {targets: {node: 'current'}}],
не уверен, что это стыкуетс яс кодстайлом: пробелы после начала и перед концом массива, как и в объекте

2021-12-28 14:36 UTC, Tenutes commented on package.json
> +    "@babel/preset-react": "^7.16.5",
убери шапочку эту

2021-12-28 14:36 UTC, Tenutes commented on package.json
> +    "@babel/preset-react": "^7.16.5",
Везде убирай)

2021-12-28 14:36 UTC, Tenutes commented on src/App.tsx
> +      привет
го без этого :D

2021-12-28 14:36 UTC, Tenutes commented on src/server-render-middleware.tsx
> +  if (context.url) {
не уверен, но, может, сначала проверим на контекст.урл, а потом будем делать рендерТуСтринг?

2022-01-02 12:27 UTC, venmovs commented on package.json
> +    "@babel/preset-react": "^7.16.5",
Убрал везде

2022-01-02 12:28 UTC, venmovs commented on babel.config.js
> +        ['@babel/preset-env', {targets: {node: 'current'}}],
поправил)

2022-01-02 12:28 UTC, venmovs commented on src/App.tsx
> +      привет
убрал)

2022-01-02 13:57 UTC, Tenutes requested changes
1 last thing

2022-01-02 13:57 UTC, Tenutes commented on babel.config.js
> +        ['@babel/preset-env', {targets: {node: 'current'}}],
неа, `{ targets: { node: 'current' }}`

2022-01-03 10:56 UTC, Tenutes approved these changes
лайк

2022-01-07 19:46 UTC, YurikEz approved these changes

2022-01-10 12:20 UTC, spt30 reviewed
пока отписал один коммент, остальное обсудим в чате

2022-01-10 12:20 UTC, spt30 commented on src/server.ts
> +}
эта функция вызывается всего один раз, причем условно
хорошо бы сделать, чтобы она либо вызывалась всегда, но возвращала иногда пустой массив, либо заинлайнить ее по месту вызова

2022-01-18 04:36 UTC, venmovs commented on src/server.ts
> +}
исправил

2022-01-18 21:03 UTC, spt30 approved these changes

2022-01-20 09:03 UTC, closed without merging