Сверстал лендинг и добавил темизацию
YaFriends/ya-game-frontend pull request #126
Opened 2022-01-11 13:45 UTC by YurikEz

#closes 99, #closes 108, #closes 109, #closes 114, #closes 122

2022-01-11 19:56 UTC, Tenutes requested changes
Я бы все-таки не дела лтемизацию чере звечную передачу параметра.
Такое лучше сделать через css-параметры: --bg-color, --text-color.
Которые менялись бы, в зависимости от текущей темы. И никакой вездесущей передачи currentTheme делать не нужно, давай попробуем.

2022-01-13 04:10 UTC, venmovs approved these changes
Лайк!

2022-01-13 16:27 UTC, Tenutes approved these changes
Аппрув

2022-01-15 08:05 UTC, spt30 requested changes
картинка static/img/icon-switch-theme.png странная
обычно там солнышко какое-то ставят или типа того,,,

2022-01-15 08:05 UTC, spt30 commented on src/App.tsx
> +  }
условно вызываемый хук — это плохо, потому что реакт полагается на последовательность их выполнения
я понимаю, что тут условие будет стабильно возвращать одно и то же значение
но все же лучше его перенести в хук

2022-01-15 08:05 UTC, spt30 commented on src/components/ui/SwitchTheme/SwitchTheme.tsx
> +        );
работу с DOM производить в реакте настоятельно не рекомендуется
лучше избегать всегда, когда есть способ избежать

тут лучше написать через ref'ы

2022-01-15 08:05 UTC, spt30 commented on src/pages/Main/Main.tsx
> +            alt="circle_triangle_square"
у вас какие-то альты ради альтов
то `icon-switch-theme`, то `circle_triangle_square`
почему не написать на русском языке и с пробелами? и вынести в TRANSLATION, соответственно

2022-01-15 08:05 UTC, spt30 commented on src/pages/Main/Main.tsx
> +          <Subtitle text={TRANSLATION.Main.teamName4} />
![image](https://user-images.githubusercontent.com/31798669/149614573-38059f56-7bbb-436c-a96e-ade0fbadb7d8.png)

2022-01-17 18:16 UTC, spt30 commented on src/components/ui/SwitchTheme/SwitchTheme.tsx
> +    (switchControl.current as unknown as HTMLElement).classList.toggle('switch-theme--open');
classList — это тоже прямая работа с DOM
лучше использовать state компонента, положить туда boolean и выставлять модификатор для элемента (блока) прямо в jsx

2022-01-18 20:12 UTC, YurikEz commented on src/components/ui/SwitchTheme/SwitchTheme.tsx
> +    (switchControl.current as unknown as HTMLElement).classList.toggle('switch-theme--open');
Готово
Переписал вообще без рефов и работой с DOM на прямую

2022-01-18 21:01 UTC, spt30 approved these changes
👍

2022-01-18 21:01 UTC, spt30 commented on src/components/ui/SwitchTheme/SwitchTheme.tsx
> +    const changeTheme: currentTheme = (target.dataset.theme as currentTheme) || darkTheme;
changed только

2022-01-18 21:01 UTC, spt30 commented on src/components/ui/SwitchTheme/SwitchTheme.tsx
> +  const classesMemoSwitchButtonTheme = (buttonTheme: string): string[] => {
тут useCallback зашел бы лучше, сразу можно было бы мемоизировать функцию и ее повызывать

2022-01-20 17:34 UTC, spt30 approved these changes

2022-01-20 20:50 UTC, merged