Adds pick/ban availability
YaFriends/ya-game-frontend pull request #127
Opened 2022-01-11 19:52 UTC by Tenutes

#closes 99

2022-01-12 21:23 UTC, YurikEz approved these changes
В целом апрув
Выглядит все окей, пару моментов на секундочку

2022-01-12 21:23 UTC, YurikEz commented on src/App.tsx
> +        <Route path="/test" component={GameSetPick} />
тут /test так и останется или будет другой ?

2022-01-12 21:23 UTC, YurikEz commented on src/pages/GameCreation/GameCreation.tsx
> +  { value: 2, label: '2', disabled: true },
тут должно быт типа 1, 3 , 5

2022-01-13 04:15 UTC, venmovs reviewed
красиво код пишите, товарищ!)

2022-01-13 04:15 UTC, venmovs approved these changes

2022-01-13 14:13 UTC, Tenutes commented on src/App.tsx
> +        <Route path="/test" component={GameSetPick} />
ой, забыл убрать))

2022-01-16 11:40 UTC, spt30 requested changes

2022-01-16 11:40 UTC, spt30 commented on src/@types/GameSet.d.ts
> +  pick?: string;
давай может переименуем как-то?
не ясно, что за параметр, тем более с типом `string`

2022-01-16 11:40 UTC, spt30 commented on src/components/GameSetHead/GameSetHead.tsx
> +  }
useMemo нужен
а лучше вообще в отдельный компонент вынести и в React.memo обернуть

2022-01-16 11:40 UTC, spt30 commented on src/components/GameSetHead/GameSetHead.tsx
> +  return <div className="game-set-top"></div>;
self-closing должен быть
какой-то линтер у вас... самозакрывающиеся теги не проверяет, undefined в jsx разрешает, мемоизацию не подсказывает

2022-01-16 11:40 UTC, spt30 commented on src/components/GameSetPick/GameSetPick.tsx
> +  const areGamesPicked = gameSet?.miniGames.length === totalMiniGames;
memo

2022-01-16 11:40 UTC, spt30 commented on src/components/GameSetPick/GameSetPick.tsx
> +  const banGame = (game: MiniGamePickInfo) => {
memo

2022-01-16 11:40 UTC, spt30 commented on src/components/GameSetPick/GameSetPick.tsx
> +  );
в целом в этом компоненте слишком много логики и списочного рендера

предлагаю разнести как-то

- сейчас все идет к тому, что хуки заменят примерно все виды side-работ над вычислениями/запросами и так далее; поэтому предлагаю тут научиться выносить логику расчетов в хуки
- а также списочный рендер мемоизировать как-нибудь — разнести в другие компоненты хорошо было бы (я бы даже прямо в этом же файле сделал)

2022-01-16 11:40 UTC, spt30 commented on src/hooks/use-game-set-session.ts
> +export const useGameSetSession = (): UseGameSetSession => {
вот тут классный хук 👍 
большой, правда

хорошо бы вот примерно в таком же стиле повытаскивать логику из GameSetHead

2022-01-16 11:40 UTC, spt30 commented on src/hooks/use-game-set-session.ts
> +      setLocalGameSet(newSet);
зачем тут слондип? почему нельзя просто сразу 
```
setLocalGameSet({ 
    ...localGameSet, 
    miniGames: [...localGameSet.miniGames, miniGame] 
});
```

2022-01-16 11:40 UTC, spt30 commented on src/hooks/use-game-set-session.ts
> +  const [localGameSet, setLocalGameSet] = useState<GameSet | null>(cloneDeep(gameSet));
тут тоже непонятно, зачем слондип нужен

2022-01-17 08:11 UTC, Tenutes commented on src/components/GameSetHead/GameSetHead.tsx
> +  }
Юзну useMemo, сам по себе MiniGamePreview - memo, и реакт не хочет возвращать его в новом компоненте как верстку

2022-01-17 08:12 UTC, Tenutes commented on src/components/GameSetHead/GameSetHead.tsx
> +  return <div className="game-set-top"></div>;
Ну линтер на это не ругатеся, так как это html, а ругается только шторм, что тег пустой

2022-01-20 17:33 UTC, spt30 approved these changes

2022-01-20 17:33 UTC, spt30 commented on src/@types/GameSet.d.ts
> +  pick_image?: string;
pick_image_url тогда уж

2022-01-22 07:16 UTC, merged