add new game (Круг Треугольник Квадрат)
YaFriends/ya-game-frontend pull request #130
Opened 2022-01-18 07:54 UTC by YurikEz

#closes 106

2022-01-18 08:12 UTC, YurikEz commented
Пока не смотрите, пока не вольют 107 тикет

2022-01-19 08:00 UTC, YurikEz commented
Теперь можно чекать

2022-01-19 13:45 UTC, Tenutes requested changes
Каефно, чучуть по переводику

2022-01-19 13:45 UTC, Tenutes commented on src/core/GameSetCoordinator.ts
> +    this.currentMiniGameIndex = 2;
Верни нолик)

2022-01-19 13:45 UTC, Tenutes commented on src/core/MiniGames/CircleTriangleSquareMiniGame.ts
> +      this.GameLoop.context.font = 'bold 24px sans-serif';
давай вынеси перед if

2022-01-19 13:45 UTC, Tenutes commented on src/core/MiniGames/CircleTriangleSquareMiniGame.ts
> +      this.GameLoop.context.font = 'bold 24px sans-serif';
+ думаю вынести этот шрифт в константы куда-то

2022-01-19 13:45 UTC, Tenutes commented on src/core/MiniGames/CircleTriangleSquareMiniGame.ts
> +      this.GameLoop.context.fillText('Ничья', 210, 75);
Весь русский текст в translation

2022-01-19 14:15 UTC, YurikEz commented on src/core/GameSetCoordinator.ts
> +    this.currentMiniGameIndex = 2;
я это оставил тк ты когда будешь пик бан игр, то тут будет какая то иная конструкция
и какой тут индекс стоит по сути все равно 
или нет ?

2022-01-19 15:05 UTC, Tenutes commented on src/core/GameSetCoordinator.ts
> +    this.currentMiniGameIndex = 2;
нет, это индекс текущей играемой игры. Он просто меняется, в зависимости от нее)

2022-01-21 04:13 UTC, Tenutes approved these changes
!

2022-01-21 04:33 UTC, venmovs approved these changes
крутота!))

2022-01-22 12:59 UTC, spt30 approved these changes

2022-01-22 12:59 UTC, spt30 commented on src/components/GameHistoryItem/GameHistoryItem.tsx
> +import { Text } from '../ui/Text/Text';
а зачем?

2022-01-22 12:59 UTC, spt30 commented on src/core/MiniGames/CircleTriangleSquareMiniGame.ts
> +    this.enemyPlayerScore = 0;
мне кажется, это лучше положить просто в переменные, нет смысла это держать в классе, вероятно

2022-01-22 13:37 UTC, YurikEz commented on src/components/GameHistoryItem/GameHistoryItem.tsx
> +import { Text } from '../ui/Text/Text';
Возможно это был линтер 
тип order

2022-01-22 13:38 UTC, YurikEz commented on src/core/MiniGames/CircleTriangleSquareMiniGame.ts
> +    this.enemyPlayerScore = 0;
Ну items и roundsWinForWin в целом можно вынести в константы
а вот currentPlayerScore и enemyPlayerScore используются для подсчета

2022-01-22 21:52 UTC, merged