Добавил XSS и CSP
YaFriends/ya-game-frontend pull request #146
Opened 2022-01-28 11:03 UTC by venmovs

Добавил защите через библиотеку [helmet](https://www.npmjs.com/package/helmet), учел новый домен. 
Еще на косяк свой наткнулся в профиле пользователя не так картинку передавал, исправил..

2022-01-28 12:45 UTC, Tenutes approved these changes
Like!

2022-01-28 14:33 UTC, YurikEz approved these changes

2022-01-30 08:10 UTC, spt30 requested changes

2022-01-30 08:10 UTC, spt30 commented on src/server.ts
> +export const nonce = crypto.randomBytes(16).toString('hex');
думаю, нельзя все запросы от разных клиентов подписывать одной подписью

давай сделаем миддлвару, которая при запросе генерирует новый nonce, подкладывает его типа в res.nonce или req.nonce, а уже helmet и server-render-middleware забирают вновь сгенерированную подпись из req/res.nonce

2022-01-31 05:03 UTC, venmovs commented on src/server.ts
> +export const nonce = crypto.randomBytes(16).toString('hex');
добавил мидлварю, которая создает nonce

2022-01-31 07:28 UTC, spt30 approved these changes

2022-02-04 09:15 UTC, merged