Sprint 5 18
YaFriends/ya-game-frontend pull request #27
Opened 2021-11-02 18:55 UTC by Tenutes

Closes #18 
--

Adds dummy routes

2021-11-02 19:06 UTC, venmovs commented on package.json
> +    "react-router-dom": "^5.3.0"
Мне кажется просто забыл убрать каретку)

2021-11-02 19:52 UTC, Tenutes commented on package.json
> +    "react-router-dom": "^5.3.0"
Yep

2021-11-03 06:50 UTC, YurikEz approved these changes

2021-11-03 09:02 UTC, venmovs approved these changes

2021-11-03 10:17 UTC, merged

2021-11-03 10:28 UTC, spt30 requested changes

2021-11-03 10:28 UTC, spt30 commented on src/App.tsx
> +  ><Component/></Route>);
роуты лучше перечислять явно, в этом есть несколько преимуществ: 
1) гарантированная проверка на существование страницы без написания сложных типов
2) рендериться может что угодно, просто компонент или функция — это разруливается разными пропсами для компонента Route
3) роуты могут быть точными и неточными, в текущем подходе часть из них будет генерироваться мапой, а часть явно — это неудобно менеджерить

2021-11-03 10:28 UTC, spt30 commented on src/App.tsx
> +  const links = pages.map(({ path, name }) => <li key={ path }><Link to={ path }>{ name }</Link></li>);
это сразу уже лучше вынести в отдельный компонент

2021-11-03 10:28 UTC, spt30 commented on src/pages/Auth/index.ts
> +  { path: '/register', component: Register, name: 'Регистрация' },
весь русский текст во всем коде лучше сразу вынести в отдельный файл (просто объект с полями — этого более чем достаточно)
если понадобится добавить перевод вашего приложения на другой язык — у вас начнутся серьезные проблемы со стоимостью разработки простой фичи

2021-11-03 10:28 UTC, spt30 commented on src/pages/Auth/index.ts
> +export default routes;
лучше совсем запретить дефолтный экспорт — эта штука от лукавого
она путает названия, не дает нормально ничего автоматически переименовать и так далее

нет ни одной причины ее использовать

2021-11-03 10:28 UTC, spt30 commented on src/pages/Dashboard/index.ts
> +export default routes;
структуру папки pages лучше сделать плоской — что-то поменяться может в любой момент; легко забыть что-то куда-то перенести и запутаться уже в самом начале

2021-11-03 10:28 UTC, spt30 commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
непонятно, почему у ребят был package-lock, а у тебя yarn.lock
кроме того, это еще и вмержилось в мастер
давайте использовать одинаковые инструменты

2021-11-03 11:49 UTC, Tenutes commented on src/App.tsx
> +  const links = pages.map(({ path, name }) => <li key={ path }><Link to={ path }>{ name }</Link></li>);
Пока эта все заглушки, все так, позже будет вынесено в header какой-нибудь, да

2021-11-03 11:50 UTC, Tenutes commented on src/pages/Auth/index.ts
> +export default routes;
Понял, принял.

2021-11-03 11:52 UTC, Tenutes commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Да, мы на созвоне как раз обсудили это, решили использовать yarn, поэтому package-lock.json удалил.

2021-11-03 11:54 UTC, Tenutes commented on src/pages/Dashboard/index.ts
> +export default routes;
Хм, понял, сделаем

2021-11-03 11:55 UTC, Tenutes commented on src/pages/Auth/index.ts
> +  { path: '/register', component: Register, name: 'Регистрация' },
Тут отмечу, что т.к. это обучающий проект, о переводе на разные языки не задумывался даже. Тогда вынесу в отдельную папку lang