add Axios and AuthController
YaFriends/ya-game-frontend pull request #32
Opened 2021-11-04 13:56 UTC by YurikEz

Добавил axios
Добавил прослойку для обращения к http запросам
Добавил API для авторизации и работе с пользователем
Добавил контролер для регистрации, авторизации и logout

closes #22, closes #23, closes #24

2021-11-04 18:10 UTC, Tenutes commented on src/utils/API.ts
> +export default axios.create({
Го без export default попробуем

2021-11-04 18:10 UTC, Tenutes commented on package.json
> +    "axios": "^0.24.0",
Давай зафиксируем версию, уберем шапочку эту, чтоб случайно не обновилось

2021-11-04 18:12 UTC, Tenutes requested changes

2021-11-04 18:12 UTC, Tenutes commented on src/controllers/AuthController.ts
> +        return await this.fetchUser();
Return await - убирай await, он лишний

2021-11-04 18:12 UTC, Tenutes commented on src/controllers/AuthController.ts
> +        return await this.fetchUser();
Убрать await

2021-11-04 18:12 UTC, Tenutes commented on src/controllers/AuthController.ts
> +      return await this.api.logout();
И тут убрать

2021-11-04 18:12 UTC, Tenutes commented on src/controllers/AuthController.ts
> +      return await this.api.read();
Ну и здесь тоже, а то двойной промис получается и нет смвсла в await совсем

2021-11-04 18:51 UTC, YurikEz commented on src/utils/API.ts
> +export default axios.create({
done

2021-11-04 18:51 UTC, YurikEz commented on package.json
> +    "axios": "^0.24.0",
done

2021-11-04 19:06 UTC, YurikEz commented on src/controllers/AuthController.ts
> +      return await this.api.logout();
done

2021-11-04 19:06 UTC, YurikEz commented on src/controllers/AuthController.ts
> +        return await this.fetchUser();
done

2021-11-04 19:07 UTC, YurikEz commented on src/controllers/AuthController.ts
> +        return await this.fetchUser();
done

2021-11-04 19:09 UTC, YurikEz commented on src/controllers/AuthController.ts
> +      return await this.api.read();
Вот тут я не особо понимаю почему ты так считаешь
1. Может быть ситуация когда надо просто вызвать этот метод и хотелось бы сделать это через промис
2. Если мы берем например Логин, где мы вызываем fetchUser в then, то надо же дождаться когда он вернется и потом идти дальше, а так получается, что если мы убираем тут async/await, то мб так, что страница отобразиться, а данные еще не пришли

2021-11-05 05:25 UTC, Tenutes commented on src/controllers/AuthController.ts
> +      return await this.api.read();
1. Функция async, она уже возвращает промис, смысла в await нет.
2.await создает промис и резолвит его, по итогу у тебя возвращается два промиса, создается он два раза, хотя достаточно было бы и просто return - поведение одно и тоже.
Вот тут написано почему это плохо и бесполезно https://kanby.medium.com/%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-return-await-%D0%BF%D0%BB%D0%BE%D1%85%D0%B0%D1%8F-%D0%B8%D0%B4%D0%B5%D1%8F-e87b70015f0c

2021-11-05 09:15 UTC, YurikEz commented on src/controllers/AuthController.ts
> +      return await this.api.read();
Этой статьи мне хватило)
Исправил

2021-11-05 17:28 UTC, Tenutes approved these changes

2021-11-05 20:31 UTC, venmovs approved these changes

2021-11-06 13:14 UTC, spt30 approved these changes
👍 очень красивая апишечка получается

2021-11-06 13:14 UTC, spt30 commented on src/api/AuthAPI.ts
> +}
хорошо бы настроить IDE так, чтобы она сама при сохранении файла добавляла новую строчку внизу файла

2021-11-06 18:28 UTC, YurikEz commented on src/api/AuthAPI.ts
> +}
Да мы никак линт еще не вольем
Скорее всего там это есть)

2021-11-06 18:30 UTC, YurikEz commented on src/api/AuthAPI.ts
> +}
В след коммитах поправим эти моменты, чтобы не стопить этот ПР

2021-11-06 18:31 UTC, merged