Sprint 5 19
YaFriends/ya-game-frontend pull request #40
Opened 2021-11-06 09:03 UTC by venmovs

Можно было конечно воспользоваться сразу готовой [библиотекой](https://github.com/bvaughn/react-error-boundary#readme), но мы вряд ли бы использовали HOC и вряд ли бы использовали некоторые props-ы из библиотеки, я вырезал все ненужное (на мой взгляд). 

Добавил компонент, который нужно отображать во время ошибок, классовый компонент error boundary и hook по аналогии из библиотеки.

Лучше реализации, чем [Кент](https://github.com/kentcdodds) не придумаю 🥲 

Closes #19

2021-11-06 09:41 UTC, YurikEz commented on src/components/error-handling/ErrorBoundary.tsx
> +        this.reset()
;

2021-11-06 09:41 UTC, YurikEz commented on src/components/error-handling/ErrorBoundary.tsx
> +        return { error }
;

2021-11-06 09:41 UTC, YurikEz commented on src/components/error-handling/ErrorBoundary.tsx
> +        this.props.onError?.(error, info)
;

2021-11-06 09:41 UTC, YurikEz commented on src/components/error-handling/ErrorBoundary.tsx
> +            this.reset()
;

2021-11-06 09:42 UTC, YurikEz commented on src/components/error-handling/ErrorBoundary.tsx
> +                return <FallbackComponent {...props} />
;

2021-11-06 09:42 UTC, YurikEz commented on src/components/error-handling/ErrorBoundary.tsx
> +                throw new Error('Requires a FallbackComponent prop')
;

2021-11-06 09:43 UTC, YurikEz commented on src/components/error-handling/ErrorBoundary.tsx
> +        return this.props.children
;

2021-11-06 09:46 UTC, YurikEz commented on src/components/error-handling/useErrorHandler.ts
> +    if (givenError != null) throw givenError;
А почему тут != (не строгое сравнение)?

Думаю нам на проекте следует придерживаться везде строго сравнения, тк мы должны самостоятельно контролировать типы (иначе зачем нам ТС) и не отдавать это на откуп JS

2021-11-06 09:46 UTC, YurikEz commented on src/components/error-handling/useErrorHandler.ts
> +    if (error != null) throw error;
Аналогично, тому что выше

2021-11-06 09:53 UTC, YurikEz reviewed
Немного натыкал там ";", в целом линтер в будущем исправит многие мелкие косячки по стайлу

В целом ок, но надо поправить некоторые моменты и обсудить их, если действительно нужно реализовать так, как и было сделано

2021-11-06 17:14 UTC, Tenutes commented on src/components/error-boundary/ErrorBoundary.tsx
> +const changedArray = (a: Array<unknown> = [], b: Array<unknown> = []) =>
Тут, я думаю, можно писать unknown[], но это придирка

2021-11-06 17:15 UTC, Tenutes commented on src/components/error-boundary/ErrorBoundary.tsx
> +const changedArray = (a: Array<unknown> = [], b: Array<unknown> = []) =>
Ну и по коду ниже так же

2021-11-06 17:16 UTC, Tenutes commented on src/components/error-boundary/ErrorBoundary.tsx
> +        prevResetKeys: Array<unknown> | undefined,
`prevResetKeys?: unknown[]`, вроде, ту же логику сделает, нет?

2021-11-06 17:21 UTC, Tenutes commented
Все ок, пару моментом подправить - откомментить и будем лить)

2021-11-07 09:31 UTC, venmovs commented on src/components/error-boundary/ErrorBoundary.tsx
> +const changedArray = (a: Array<unknown> = [], b: Array<unknown> = []) =>
исправил везде)

2021-11-07 09:34 UTC, venmovs commented on src/components/error-boundary/ErrorBoundary.tsx
> +        prevResetKeys: Array<unknown> | undefined,
вопрос не совсем понял :(

2021-11-08 06:44 UTC, YurikEz approved these changes

2021-11-10 09:23 UTC, Tenutes approved these changes

2021-11-10 09:23 UTC, Tenutes commented on src/components/error-boundary/useErrorHandler.ts
> +        && typeof givenError === 'string') throw new Error(givenError);
если `givenError === 'string'`, то проверка на null - лишняя.

2021-11-10 09:23 UTC, Tenutes commented on src/lang/ru/translation.ts
> +  TryAgain: 'Попробовать сново',
снов`а` 👯

2021-11-10 09:23 UTC, Tenutes commented on src/components/error-boundary/ErrorBoundary.tsx
> +        prevResetKeys: Array<unknown> | undefined,
Ну ты пишешь: prevResetKey - это или неизвестный массив, или undefined, prevResetkeys?: unknown[] как раз то же самое и делает

2021-11-10 16:37 UTC, spt30 requested changes

2021-11-10 16:37 UTC, spt30 commented on src/App.tsx
> +};
а это ты руками поправил или новый линтер по-новому метет?

2021-11-10 16:37 UTC, spt30 commented on src/components/error-handling/ErrorBoundary.tsx
> +    a.length !== b.length || a.some((item, index) => !Object.is(item, b[index]));
уверен, что `Object.is()`, а не `===`?

2021-11-10 16:37 UTC, spt30 commented on src/components/error-handling/ErrorFallback.tsx
> +const ErrorFallback: FC<FallbackProps> = ({error, resetErrorBoundary}) => {
что-то я не вижу, где эта штука используется (как и ErrorBoundary)
давай для начала на App.tsx ее навесим, чтобы посмотреть, насколько это красиво вообще

2021-11-10 16:37 UTC, spt30 commented on src/components/error-handling/ErrorBoundary.tsx
> +                return <FallbackComponent {...props} />
так делать вообще говоря не очень хорошо
тут по сути ты жестко задаешь сигнатуру компонента FallbackComponent
давай тут применим https://ru.reactjs.org/docs/render-props.html

снаружи будет как-то так
```
<ErrorBoundary
    renderFallback={(error, resetErrorBoundary) => {
        return (
            /* а тут мы можем отрендерить любой компонент и воспользоваться или не воспользоваться аргументами*/
            <div>все очень плохо</div>
        )
    }}
    ...
```

2021-11-10 16:37 UTC, spt30 commented on src/components/error-handling/ErrorFallback.tsx
> +            <pre>{error.message || error}</pre>
а давай еще в консоль писать console.error(error), чтобы дебажить проще было если что
можно через if (process.env.NODE_ENV === 'develop') или как-нибудь так

2021-11-10 16:37 UTC, spt30 commented on src/components/error-handling/ErrorBoundary.tsx
> +const changedArray = (a: unknown[] = [], b: unknown[] = []) =>
обычно такие функции (которые возвращают boolean) называются с is, has, have
тут подойдет isArrayChanged

2021-11-11 04:58 UTC, venmovs commented on src/App.tsx
> +};
Это старый линтер, если он тогда вообще был)

2021-11-11 05:04 UTC, venmovs commented on src/components/error-handling/ErrorBoundary.tsx
> +    a.length !== b.length || a.some((item, index) => !Object.is(item, b[index]));
выглядит так, будто можно поменять, но так было в решении ребят, и я подумал, что они допускают более изощренные сравнения

2021-11-11 05:13 UTC, venmovs commented on src/components/error-handling/ErrorBoundary.tsx
> +                return <FallbackComponent {...props} />
Мне кажется удобнее будет передавать компонент через пропс, не? С учетом того, что мы не так часто будем оборачивать части приложения с помощью errorBoundry

2021-11-11 05:28 UTC, venmovs commented on src/components/error-handling/ErrorFallback.tsx
> +            <pre>{error.message || error}</pre>
в консоли и так пишутся ошибки, которые произошли, это ведь исключительно клиентская часть

2021-11-11 05:29 UTC, venmovs commented on src/components/error-handling/ErrorFallback.tsx
> +const ErrorFallback: FC<FallbackProps> = ({error, resetErrorBoundary}) => {
👀

2021-11-11 05:29 UTC, venmovs commented on src/components/error-handling/ErrorBoundary.tsx
> +const changedArray = (a: unknown[] = [], b: unknown[] = []) =>
👀

2021-11-13 13:02 UTC, spt30 commented on src/components/error-handling/ErrorBoundary.tsx
> +                return <FallbackComponent {...props} />
Через пропс у тебя пропадает точка расширения функциональности
При прочих равных, если есть возможность оставить такую точку, то лучше ее оставить

2021-11-16 06:09 UTC, venmovs commented on src/components/error-handling/ErrorBoundary.tsx
> +                return <FallbackComponent {...props} />
Переделал!)

2021-11-17 17:18 UTC, spt30 approved these changes

2021-11-17 17:18 UTC, spt30 commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +): React.ReactElement<unknown, string | React.FunctionComponent | typeof React.Component> | null;
просто `fallbackRender: (props: FallbackProps) => ReactNode`
не нужны тут эти танцы с типами

2021-11-17 17:18 UTC, spt30 commented on src/App.tsx
> +        </div>
красивое....

2021-11-22 07:33 UTC, merged