add ui Components - Button, Title, Subtitle
YaFriends/ya-game-frontend pull request #48
Opened 2021-11-06 23:19 UTC by YurikEz

Closes #45, Closes #43, Closes #42

2021-11-06 23:47 UTC, YurikEz commented
Closes #49, Closes #50, Closes #51

2021-11-07 09:26 UTC, YurikEz commented on src/components/ui/Button/Button.tsx
> +      <span className={ 'container' }>{ text }</span>
Исправил

2021-11-07 09:27 UTC, Tenutes approved these changes

2021-11-07 09:53 UTC, venmovs commented on src/components/ui/Button/Button.tsx
> +      <span className={ 'container' }>{ text }</span>
Если в className у span-а будет статический класс, то можно передать без фигурных кавычек, типо такого <span className='container'>{ text }</span>

2021-11-07 09:54 UTC, venmovs approved these changes

2021-11-07 17:14 UTC, spt30 requested changes
<img width="815" alt="Снимок экрана 2021-11-07 в 21 59 10" src="https://user-images.githubusercontent.com/31798669/140654330-2c2b7b54-435d-4766-b283-f7a3c765be25.png">
Думаю, что svg-шрифты не нужны
Да и вообще, я бы только woff2 оставил, но тут уже не важно, кажись, пусть будет так

Комменты где-то на всякий случай задублировал, но вообще все комменты постарайтесь распространить на весь код (особенно про БЭМ)

2021-11-07 17:14 UTC, spt30 commented on src/components/ui/Button/Button.tsx
> +  const defaultClassNames = [
<img width="582" alt="Снимок экрана 2021-11-07 в 22 03 30" src="https://user-images.githubusercontent.com/31798669/140654471-b1b5d2f8-45cc-49b4-9294-d2c7d78269f0.png">
Это линтер так сделал? Давайте как-то это отформатируем нормально

2021-11-07 17:14 UTC, spt30 commented on src/components/ui/Button/Button.tsx
> +  ];
это можно вынести за пределы класса в начало файла

2021-11-07 17:14 UTC, spt30 commented on src/components/ui/Button/Button.tsx
> +      }
такую канитель лучше сразу выносить в хорошо именнованный хэлпер, чтобы не приходилось вчитываться каждый раз, когда хочется посмотреть этот компонент

2021-11-07 17:14 UTC, spt30 commented on src/components/ui/Button/Button.tsx
> +      <span className="container">{ text }</span>
слишком общий className
вроде вас просят придерживаться БЭМ, здесь он не соблюдается
для удобства есть библиотека https://ru.bem.info/technologies/bem-react/classname/

2021-11-07 17:14 UTC, spt30 commented on src/components/ui/Input/Input.tsx
> +  const classes = [defaultClasses, errorClasses || successClasses || disabledClasses].join(' ');
здесь хорошо бы мемоизировать данные с помощью хуйков
а также вынести за пределы класса статические переменные, чтобы они каждый раз не создавались заново, и назвать их в CONSTANT_CASE

2021-11-07 17:14 UTC, spt30 commented on src/components/ui/Input/Input.tsx
> +  const classes = [defaultClasses, errorClasses || successClasses || disabledClasses].join(' ');
тоже в хэпер вынести такую логику лучше
она напрямую не относится к компоненту и выглядит как вполне себе переиспользуемая

2021-11-07 17:14 UTC, spt30 commented on src/components/ui/Input/Input.tsx
> +      { label && <label className={ labelClasses } htmlFor={ id || name }>{ label } </label> }
такие штуки лучше выносить в компоненты-элементы (такие же компоненты, только маленькие, прямо рядом в этом же файле); я их обычно именую с суффиксом Element, чтобы не было желания переиспользовать его где-то еще ненароком

так будет возможность контролировать рендеринг и не перерендеривать весь компонент целиком

2021-11-07 22:09 UTC, YurikEz commented on src/components/ui/Button/Button.tsx
> +  const defaultClassNames = [
ага, линтер, думаю в последующих пр поправим линтер
чтобы не стопить этот ПР

2021-11-07 22:09 UTC, YurikEz commented on src/components/ui/Button/Button.tsx
> +  ];
Вынес

2021-11-07 22:10 UTC, YurikEz commented on src/components/ui/Button/Button.tsx
> +      <span className="container">{ text }</span>
Это класс tailwild
исправил на другой
пока ждем решения по поводу бэм и тд

2021-11-08 05:20 UTC, YurikEz commented on src/components/ui/Button/Button.tsx
> +      }
готово

2021-11-08 05:20 UTC, YurikEz commented on src/components/ui/Input/Input.tsx
> +  const classes = [defaultClasses, errorClasses || successClasses || disabledClasses].join(' ');
готово

2021-11-08 06:04 UTC, YurikEz commented on src/components/ui/Input/Input.tsx
> +      { label && <label className={ labelClasses } htmlFor={ id || name }>{ label } </label> }
готово

2021-11-08 06:04 UTC, YurikEz commented on src/components/ui/Input/Input.tsx
> +  const classes = [defaultClasses, errorClasses || successClasses || disabledClasses].join(' ');
готово

2021-11-08 07:38 UTC, venmovs approved these changes

2021-11-08 13:23 UTC, Tenutes approved these changes

2021-11-08 16:58 UTC, spt30 approved these changes

2021-11-08 17:17 UTC, merged