review components & add Login layout
YaFriends/ya-game-frontend pull request #52
Opened 2021-11-07 14:37 UTC by YurikEz

Closes #17

2021-11-08 17:30 UTC, venmovs approved these changes

2021-11-08 19:06 UTC, Tenutes commented on src/pages/Login/Login.tsx
> +  const handleClick = (e: MouseEvent) => {
го handleLogin

2021-11-08 19:08 UTC, Tenutes approved these changes

2021-11-08 19:28 UTC, YurikEz commented on src/pages/Login/Login.tsx
> +  const handleClick = (e: MouseEvent) => {
Когда будем писать логику осмыслим, пока пусть будет так

2021-11-08 19:31 UTC, spt30 requested changes

2021-11-08 19:31 UTC, spt30 commented on src/pages/Login/Login.tsx
> +      </div>
Уже писал про то, что кириллицу лучше вынести в отдельный файл с ключами
Кстати, он у вас уже есть

2021-11-08 19:32 UTC, spt30 commented on src/pages/Login/Login.tsx
> +        <MainLink text="Вернуться на главную" href="/" />
тут бессмысленно добавлять "wrapper" к названию класса, давай его уберем
вообще это моветон, точно так же, как использовать data в названии переменной и list в именовании массива

2021-11-09 04:53 UTC, YurikEz commented on src/pages/Login/Login.tsx
> +  const handleClick = (e: MouseEvent) => {
готово

2021-11-09 05:07 UTC, YurikEz commented on src/pages/Login/Login.tsx
> +      </div>
готово

2021-11-09 05:08 UTC, YurikEz commented on src/pages/Login/Login.tsx
> +        <MainLink text="Вернуться на главную" href="/" />
готово

2021-11-10 16:25 UTC, spt30 approved these changes
👍 агонь!

2021-11-10 16:25 UTC, spt30 commented on src/components/ui/Form/Form.tsx
> +  return result;
у вас же вроде уже есть похожий хэлпер где-то

2021-11-10 16:38 UTC, YurikEz commented on src/components/ui/Form/Form.tsx
> +  return result;
В каждом компоненте есть такой кусок, надо бы вынести в хелпер
Создам таску

2021-11-10 16:51 UTC, merged