add Register.tsx layout
YaFriends/ya-game-frontend pull request #53
Opened 2021-11-08 15:50 UTC by YurikEz

Closes #16

2021-11-08 17:28 UTC, venmovs approved these changes

2021-11-08 19:07 UTC, Tenutes commented on src/pages/Register/Register.tsx
> +  const handleClick = (e: MouseEvent) => {
ну и тут handleSignUp(handleSubmit), что-то осмысленное

2021-11-08 19:07 UTC, Tenutes approved these changes

2021-11-08 19:27 UTC, YurikEz commented on src/pages/Register/Register.tsx
> +  const handleClick = (e: MouseEvent) => {
это пока заготовка, когда будем писать логику - осмыслим

2021-11-08 19:34 UTC, spt30 requested changes

2021-11-08 19:34 UTC, spt30 commented on src/pages/Register/Register.tsx
> +        <Input name="password" label="Пароль" placeholder="Введите пароль" required />
хорошо бы form-input-wrapper вынести в отдельный компонент, чтобы не пришлось править в 10 местах потом

2021-11-08 19:34 UTC, spt30 commented on src/pages/Register/Register.tsx
> +      <form className="register__form" name="registerForm">
можно даже на самом деле сделать отдельный компонент формочки, в который напихать инпуты и кнопки  и отрендерить с помощью https://reactjs.org/docs/react-api.html#reactchildrenmap

если будешь так делать — в https://github.com/YaFriends/ya-game-frontend/pull/52/files тоже надо будет

2021-11-09 06:35 UTC, YurikEz commented on src/pages/Register/Register.tsx
> +  const handleClick = (e: MouseEvent) => {
готово

2021-11-09 06:38 UTC, YurikEz commented on src/pages/Register/Register.tsx
> +        <Input name="password" label="Пароль" placeholder="Введите пароль" required />
Создал общий компонент формы и там генерирую инпуты и кнопки

2021-11-09 06:38 UTC, YurikEz commented on src/pages/Register/Register.tsx
> +      <form className="register__form" name="registerForm">
Сделал немного иначе
через генерацию инпутов и кнопок из массива

2021-11-09 06:50 UTC, venmovs approved these changes

2021-11-09 08:26 UTC, YurikEz commented on src/pages/Register/Register.tsx
> +      <form className="register__form" name="registerForm">
После обсуждений, сделал через react.children.map

2021-11-10 16:24 UTC, spt30 approved these changes

2021-11-10 16:55 UTC, merged