add Leaderboard layout + API + Controller
YaFriends/ya-game-frontend pull request #54
Opened 2021-11-08 19:26 UTC by YurikEz

Closes #20

2021-11-09 10:50 UTC, venmovs approved these changes

2021-11-10 09:55 UTC, Tenutes commented on src/pages/Leaderboard/Leaderboard.scss
> +    width: 50%;
w-half / w-1/2

2021-11-10 09:57 UTC, Tenutes requested changes

2021-11-10 09:57 UTC, Tenutes commented on src/pages/Leaderboard/Leaderboard.scss
> +    height: 300px;
h-[300px]

2021-11-10 16:40 UTC, Tenutes approved these changes

2021-11-10 19:25 UTC, Tenutes commented on src/components/ui/Table/ElementTableBody.tsx
> +  return <tbody className={DEFAULT_CLASSES.join(' ')}>{getBody()}</tbody>;
не нужна функция, оставь только map и его и передай)

2021-11-10 19:27 UTC, Tenutes requested changes

2021-11-10 19:27 UTC, Tenutes commented on src/components/ui/Table/ElementTableHead.tsx
> +  const getHeaders = (): ReactNode => headers.map((item, index) => createHead(item, index));
ну и тут тоже

2021-11-10 19:27 UTC, Tenutes commented on src/components/ui/Table/ElementTableRow.tsx
> +  const getRow = (): ReactNode => row.map((text, index) => createCell(text, index));
и тут тоже

2021-11-10 19:27 UTC, Tenutes commented on src/pages/Leaderboard/Leaderboard.tsx
> +  ['Позиция #', 'border w-[150px] bg-grey40'],
Все текстовки бери из translations

2021-11-10 19:27 UTC, Tenutes commented on src/pages/Leaderboard/Leaderboard.tsx
> +    useState<PositionLeaderboardText>('Тебя нет в таблице');
и тут тож

2021-11-11 05:02 UTC, YurikEz commented on src/pages/Leaderboard/Leaderboard.tsx
> +  ['Позиция #', 'border w-[150px] bg-grey40'],
Да да опять забыл чет
сам себе говорил надо заменить ) 
ща сделаю

2021-11-11 09:19 UTC, Tenutes approved these changes

2021-11-11 09:38 UTC, venmovs approved these changes

2021-11-11 18:15 UTC, spt30 approved these changes

2021-11-11 18:15 UTC, spt30 commented on src/components/ui/Table/ElementTableRow.tsx
> +  const getRow = row.map((text, index) => createCell(text, index));
эти функции лучше мемоизировать

2021-11-12 14:18 UTC, spt30 approved these changes

2021-11-12 14:22 UTC, merged