Add Dashboard page, Profile Game History page, copyPlugin, postcss plugin
YaFriends/ya-game-frontend pull request #58
Opened 2021-11-10 16:51 UTC by Tenutes

Closes #13, Closes #10

2021-11-11 05:43 UTC, YurikEz reviewed
Гуд джоб
Чуть - чуть подправить и в прод

2021-11-11 05:43 UTC, YurikEz commented on src/components/GameHistoryList/GameHistoryList.tsx
> +export type LeaderboardListProps = {
Переименовать тип

2021-11-11 05:43 UTC, YurikEz commented on src/components/GameHistoryList/GameHistoryList.tsx
> +export const GameHistoryList: FC<LeaderboardListProps> = ({ items, link }) => {
И тут

2021-11-11 05:43 UTC, YurikEz commented on src/components/GameHistoryList/GameHistoryList.tsx
> +          {items.map(item => (
Я бы вынес в переменную или функцию, чтобы верстка была менее нагруженной от мапов и тд

2021-11-11 05:43 UTC, YurikEz commented on src/components/GameHistoryItem/GameHistoryItem.tsx
> +      <p className={`game-history-item__result game-history-item__result--${result.type}`}>
Этот P можно заменить компонентом Subtitle, хотя наверное это будет симантически не верно
Можно попробовать расширить компонент Text и дать возможность передавать туда размер шрифта и тогда можно будет его заюзать

2021-11-11 05:43 UTC, YurikEz commented on src/components/Profile/Profile.tsx
> +          <p className="profile__login">{user.login}</p>
Заменить на компонент Subtitle, либо обновить компонент Text как описал выше

2021-11-11 05:43 UTC, YurikEz commented on src/components/Profile/Profile.tsx
> +          <p className="profile__win-stat">
Использовать компонент Description

2021-11-11 05:43 UTC, YurikEz commented on tailwind.config.js
> +        light: '#C4C4C4',
а этот цвет откуда? Вроде в фигме такого нет )

2021-11-11 05:43 UTC, YurikEz commented on src/components/GameHistoryList/GameHistoryList.tsx
> +  link: JSX.Element;
А почему не ReactNode ?

2021-11-11 07:48 UTC, Tenutes commented on tailwind.config.js
> +        light: '#C4C4C4',
Есть :) в картинке профиля

2021-11-11 07:49 UTC, Tenutes commented on src/components/GameHistoryList/GameHistoryList.tsx
> +  link: JSX.Element;
Такую штуку предложил storm - попробую ноду тогда

2021-11-11 08:58 UTC, YurikEz commented on tailwind.config.js
> +        light: '#C4C4C4',
я думаю можно обычный серый тк это просто заглушка и в целом все равно какой там будет цвет

2021-11-11 08:59 UTC, YurikEz commented on src/components/GameHistoryList/GameHistoryList.tsx
> +  link: JSX.Element;
А я думал ты знаешь что то секретное
тк я видел в разных примерах именно ReactNode

2021-11-11 09:24 UTC, Tenutes commented on src/components/GameHistoryItem/GameHistoryItem.tsx
> +      <p className={`game-history-item__result game-history-item__result--${result.type}`}>
Обновил компонент Text

2021-11-11 13:49 UTC, YurikEz approved these changes
Класс

2021-11-11 14:20 UTC, venmovs approved these changes

2021-11-11 18:16 UTC, spt30 requested changes

2021-11-11 18:16 UTC, spt30 commented on src/components/GameHistoryItem/GameHistoryItem.tsx
> +  const versus = teams.map(({ players }) => players.join(', ')).join(' vs ');
используй хуки для мемоизации
а еще лучше дполнительно вынести в отдельный компонент

2021-11-11 18:36 UTC, Tenutes commented on src/components/GameHistoryItem/GameHistoryItem.tsx
> +  const versus = teams.map(({ players }) => players.join(', ')).join(' vs ');
Добавил memo. Т.к. на данный момент как `gameGroup`, так и `versus` будут использоваться только в `GameHistoryItem`, и нет задумки их где-то еще переиспользовать, то не ххочется выносить в отдельный компонент

2021-11-11 21:18 UTC, venmovs approved these changes

2021-11-12 07:43 UTC, spt30 commented on src/components/GameHistoryItem/GameHistoryItem.tsx
> +  const versus = teams.map(({ players }) => players.join(', ')).join(' vs ');
Смысл в том, что у тебя сейчас при изменении одной игры, перерендерится весь список — это не есть хорошо
Компоненты нужны не только для переиспользования, но еще и для оптимизации перерисовки, так что аргумент невалидный

2021-11-12 09:40 UTC, spt30 approved these changes

2021-11-12 09:41 UTC, merged