Created Profile and GameCreation page
YaFriends/ya-game-frontend pull request #66
Opened 2021-11-14 14:23 UTC by venmovs

Сделал

1.  Страницу Profile
2. Страницу GameCreation
3. Добавил в компонент Button пропс id чтобы вне Form можно было использовать, как button submit
4. В Input компонент добавил пропсы, чтобы инпуты были контролируемыми
5. Переделал немного стили для Select и добавил свойство disabled для options

Closes #12 #9

2021-11-14 14:38 UTC, Tenutes commented on src/api/UserAPI.ts
> +  [key: string]: string | number;
А есть ли тогда смысл во всех верхних полях?)

2021-11-14 14:38 UTC, Tenutes commented on src/pages/Profile/UserThumbnail.tsx
> +import React, { FC } from 'react';
Этот компонент уже есть у меня, заменим позже)

2021-11-14 15:11 UTC, venmovs commented on src/pages/Profile/UserThumbnail.tsx
> +import React, { FC } from 'react';
хорошо)

2021-11-15 04:46 UTC, venmovs commented on src/api/UserAPI.ts
> +  [key: string]: string | number;
Ну да, тс ведь оставляет доступ к верхним полям + типизирует ключи, если есть другая возможность объяснить тс, что ключи это string, то буду благодарен совету)

2021-11-15 06:03 UTC, Tenutes commented on src/api/UserAPI.ts
> +  [key: string]: string | number;
Ну т.к. это конкретный объект юзера - то яб их напрямую перечислил

2021-11-15 18:59 UTC, YurikEz reviewed
Ну пока что так
У нас с Романом вроде +- получается в одном стиле писать
У тебя немного отличается было бы хорошо, если бы ты смог писать более приближенно к нашему стилю, чтобы код был более однообразным
Но это скорее так доебка, чем действительное замечание

В целом все хорошо, немного поправить и в прод :)

2021-11-15 18:59 UTC, YurikEz commented on src/components/ui/Form/Form.tsx
> +    <form name={name} className={classesMemo.join(' ')} id={id} onSubmit={submit}>
В целом у тебя name у формы должен быть уникальным, можно либо находить форму по name
ну или присваивать name в атрибут id

2021-11-15 18:59 UTC, YurikEz commented on src/components/ui/Button/Button.tsx
> +  } else {
Это не нужно, тк если нет typeAction, то кнопка должна быть и так синей

2021-11-15 18:59 UTC, YurikEz commented on src/api/UserAPI.ts
> +  [key: string]: string | number;
У тебя по идее и так все поля тут должны быть, какие ключи там еще нужны ?

2021-11-15 18:59 UTC, YurikEz commented on src/components/GameHistoryItem/GameHistoryItem.tsx
> +  const gameGroup = games.map(({ id, name, icon }) => (
Я бы наверно это вынес из GameHistoryItem выше и описал тоже как функц компонент, на подобии того, как я делал в leaderboard

2021-11-15 18:59 UTC, YurikEz commented on src/components/ui/Input/Input.tsx
> +  onChange?: (event: ChangeEvent<HTMLInputElement>) => void;
Здесь я думаю лучше будет так change?: (e: FormEvent) => void;
тип FormEvent берешь отсюда  import React, { FC, FormEvent, useMemo } from 'react';

2021-11-15 18:59 UTC, YurikEz commented on src/components/ui/Input/Input.tsx
> +  onChange?: (event: ChangeEvent<HTMLInputElement>) => void;
и переименуй плз в просто change
я у себя тож добавлял просто )

2021-11-15 18:59 UTC, YurikEz commented on src/pages/Profile/Profile.tsx
> +          <div className="profile__menu">
я бы наверное верстку для конкретных роутов вынес бы в отдельные компоненты
так слишком нагружено на мой взгляд

2021-11-15 19:41 UTC, venmovs commented on src/api/UserAPI.ts
> +  [key: string]: string | number;
@YurikEz больше никаких ключей не нужно, я не знал как иначе обьяснить TS, что ключи у данного интерфейса стринговые

2021-11-16 04:17 UTC, venmovs commented on src/components/ui/Form/Form.tsx
> +    <form name={name} className={classesMemo.join(' ')} id={id} onSubmit={submit}>
Убрал id пропс

2021-11-16 04:19 UTC, venmovs commented on src/components/GameHistoryItem/GameHistoryItem.tsx
> +  const gameGroup = games.map(({ id, name, icon }) => (
Я не понимаю почему это попало в мой коммит, но это изменения Ромы

2021-11-16 04:19 UTC, venmovs commented on src/components/ui/Input/Input.tsx
> +  onChange?: (event: ChangeEvent<HTMLInputElement>) => void;
Изменил все :)

2021-11-16 04:19 UTC, venmovs commented on src/pages/Profile/Profile.tsx
> +          <div className="profile__menu">
Вынес)

2021-11-16 04:27 UTC, venmovs commented on src/components/ui/Button/Button.tsx
> +  } else {
@YurikEz я убирал в DEFAULT_CLASSES синий и добавлял его, если нету typeAction, иначе у меня перетирался зеленый цвет синим. Что я делаю не так? :((

2021-11-16 15:37 UTC, YurikEz commented on src/components/GameHistoryItem/GameHistoryItem.tsx
> +  const gameGroup = games.map(({ id, name, icon }) => (
Возможно тебе надо обновить мастер 
и залить мастер к себе в ветку
и тогда мб будет меньше изменений тут отражено

2021-11-16 21:17 UTC, venmovs commented on src/api/UserAPI.ts
> +  [key: string]: string | number;
Благодаря Роме исправил это)

2021-11-17 07:22 UTC, YurikEz commented on src/components/ui/Form/Form.tsx
> +    <form name={name} className={classesMemo.join(' ')} id={id} onSubmit={submit}>
хм, тут все еще есть

2021-11-17 07:23 UTC, Tenutes approved these changes
Nice

2021-11-17 07:23 UTC, YurikEz commented on src/components/ui/Button/Button.tsx
> +  } else {
Да, то что касается цветов надо перенести внутрь файла Button.scss
и там где .ui-button
сделать так @apply (тут идут эти классы с цветом)

и тогда по идее перетирать не будет

2021-11-17 07:25 UTC, YurikEz commented on src/components/ui/Button/Button.tsx
> +  } else {
https://github.com/YaFriends/ya-game-frontend/pull/69/files#diff-f2c0746d2880913aaabb9983e123a3d5e92a1a6a78c4aa9a1896382528106ee6
https://github.com/YaFriends/ya-game-frontend/pull/69/files#diff-f2c0746d2880913aaabb9983e123a3d5e92a1a6a78c4aa9a1896382528106ee6
Вот ссылочки как это сделано в моем ПР

2021-11-17 09:36 UTC, venmovs commented on src/components/ui/Form/Form.tsx
> +    <form name={name} className={classesMemo.join(' ')} id={id} onSubmit={submit}>
я присвоил name в атрибут id

2021-11-17 09:36 UTC, venmovs commented on src/components/ui/Button/Button.tsx
> +  } else {
Исправил)

2021-11-17 09:38 UTC, YurikEz commented on src/components/ui/Form/Form.tsx
> +    <form name={name} className={classesMemo.join(' ')} id={id} onSubmit={submit}>
Да, четко

2021-11-17 09:39 UTC, YurikEz approved these changes
Гуд
В прод!

2021-11-17 16:29 UTC, spt30 requested changes

2021-11-17 16:29 UTC, spt30 commented on src/pages/Profile/InformationForm.tsx
> +    setInputsAttributes(copyState);
Такое копирование не сработает
У тебя создастся новый массив, да, но ссылки на объекты внутри будут те же самые

2021-11-17 16:29 UTC, spt30 commented on src/pages/Profile/InformationForm.tsx
> +      return copyState;
тут тоже

2021-11-17 16:29 UTC, spt30 commented on src/pages/Profile/InformationForm.tsx
> +    setInputsAttributes(prevState => prevState);
что это?

2021-11-17 16:29 UTC, spt30 commented on src/pages/Profile/InformationForm.tsx
> +      {renderInputs}
с глагола обычно именуются функции, в данном случае это массив
лучше переименовать

2021-11-17 16:29 UTC, spt30 commented on src/pages/Profile/PasswordForm.tsx
> +        return copyState;
и тут

2021-11-17 16:29 UTC, spt30 commented on src/pages/Profile/PasswordForm.tsx
> +      return copyState;
и тут

2021-11-17 16:29 UTC, spt30 commented on src/pages/Profile/settings/ChangePassword.tsx
> +      </div>
здесь элементы используются без блока
это не по БЭМу

2021-11-17 16:29 UTC, spt30 commented on src/pages/Profile/settings/EditInfo.tsx
> +      </div>
тоже не по бэму

2021-11-17 16:29 UTC, spt30 commented on src/pages/Profile/settings/Settings.tsx
> +      </div>
тоже)

2021-11-18 06:46 UTC, venmovs commented on src/pages/Profile/InformationForm.tsx
> +    setInputsAttributes(copyState);
изменил реализацию

2021-11-18 06:48 UTC, venmovs commented on src/pages/Profile/InformationForm.tsx
> +    setInputsAttributes(prevState => prevState);
Переименовал название функции, удалил  `setInputsAttributes(prevState => prevState);`

Если я правильно понял этот развернутый вопрос 😄

2021-11-18 06:49 UTC, venmovs commented on src/pages/Profile/InformationForm.tsx
> +      {renderInputs}
переименовал

2021-11-18 06:49 UTC, venmovs commented on src/pages/Profile/settings/ChangePassword.tsx
> +      </div>
переделал

2021-11-18 16:43 UTC, spt30 approved these changes

2021-11-22 07:34 UTC, merged