Create sort method
YaFriends/ya-game-frontend pull request #68
Opened 2021-11-15 21:24 UTC by venmovs

Closes #60

2021-11-16 08:07 UTC, YurikEz approved these changes
Все круто, оставил комменты они не критичные, некоторые надо за тестить не совсем уверен, что так будет работать

В целом можно и ничего не делать, сорт отличный )

2021-11-16 08:07 UTC, YurikEz commented on src/utils/sort.ts
> +    for (let i = start; i < end; i += 1) {
i += 1 => i++ - должно быть одно и тоже
нам же надо на 1 увеличить

2021-11-16 08:07 UTC, YurikEz commented on src/utils/sort.ts
> +        splitIndex += 1;
аналогично, можно написать splitIndex++

2021-11-16 08:07 UTC, YurikEz commented on src/utils/sort.ts
> +    recursiveSort(start, splitIndex - 1);
и тут splitIndex--

2021-11-16 08:07 UTC, YurikEz commented on src/utils/sort.ts
> +    recursiveSort(splitIndex + 1, end);
и тут. splitIndex++

2021-11-16 14:58 UTC, Tenutes commented on src/utils/sort.ts
> +    for (let i = start; i < end; i += 1) {
yep

2021-11-16 14:59 UTC, Tenutes commented on src/utils/sort.ts
> +    recursiveSort(start, splitIndex - 1);
Не согласен. Тут просто передается индекс, на 1 меньше, не изменяется.

2021-11-16 14:59 UTC, Tenutes commented on src/utils/sort.ts
> +    recursiveSort(splitIndex + 1, end);
А тут просто увеличивается

2021-11-16 15:02 UTC, Tenutes approved these changes
Все нормалды.

2021-11-16 15:09 UTC, YurikEz commented on src/utils/sort.ts
> +    recursiveSort(start, splitIndex - 1);
соглы, не смотреть сюда

2021-11-16 15:10 UTC, YurikEz commented on src/utils/sort.ts
> +    recursiveSort(splitIndex + 1, end);
соглы, не смотреть сюда

2021-11-16 21:21 UTC, venmovs commented on src/utils/sort.ts
> +        splitIndex += 1;
изменил)

2021-11-16 21:21 UTC, venmovs commented on src/utils/sort.ts
> +    for (let i = start; i < end; i += 1) {
изменил)

2021-11-17 16:40 UTC, spt30 requested changes
в задаче написано, что метод должен быть описан в прототипе
реализации не вижу

2021-11-17 16:40 UTC, spt30 commented on src/utils/sort.ts
> +}
хорошо бы определиться, стрелочные функции писать или обычные

2021-11-17 16:40 UTC, spt30 commented on src/utils/sort.ts
> +export type Comparator = <T>(a: T, b: T) => SortingPosition;
а зачем этот тип экспортируется?

2021-11-17 16:40 UTC, spt30 commented on src/utils/sort.ts
> +  array[secondIndex] = temp;
поскольку задача предполагается на алгоритмы, можно я скажу что такой способ менять элементы местами является 
1. неоптимальным по памяти
2. некрасивым

давай сделаем его хотя бы каким-нибудь

2021-11-17 16:40 UTC, spt30 commented on src/utils/sort.ts
> +  const sortedArray = [...array];
дефолтный метод сортировки предполагает, что массив мутируется

2021-11-17 16:40 UTC, spt30 commented on src/utils/sort.ts
> +export const sort: Sort = <T>(array: T[], comparator = defaultComparator): T[] => {
не понятно, зачем тут что-то импортируется наружу

2021-11-21 16:52 UTC, spt30 commented on src/utils/customSort.ts
> +export {};
линтер?

2021-11-21 16:52 UTC, spt30 commented on src/utils/customSort.ts
> +export {};
Давай вырубим его, это дичь

2021-11-21 16:52 UTC, spt30 commented on src/utils/customSort.ts
> +};
давай сделаем консистентный со стандартным метод — он предполагает лексикографическую сортировку по умолчанию

2021-11-21 16:52 UTC, spt30 commented on src/index.tsx
> +import '../src/utils/customSort';
👍

2022-02-09 19:31 UTC, YurikEz commented
не актуально

2022-02-09 19:31 UTC, closed without merging