Авторизация/Регистрация в проекте
YaFriends/ya-game-frontend pull request #69
Opened 2021-11-16 09:37 UTC by YurikEz

Closes #56, closes #14, closes #15

2021-11-16 14:50 UTC, Tenutes commented on src/controllers/AuthController.ts
> +      .then(response => getData(response))
убирай, делай пока просто `({data}) => data`

2021-11-16 14:57 UTC, Tenutes requested changes

2021-11-16 14:57 UTC, Tenutes commented on src/controllers/LeaderboardController.ts
> +      .then(response => getData(response))
И тут тоже давай уберем

2021-11-16 14:57 UTC, Tenutes commented on src/controllers/LeaderboardController.ts
> +      .then(response => getData(response))
и тут

2021-11-16 14:57 UTC, Tenutes commented on src/controllers/LeaderboardController.ts
> +      .then(response => getData(response))
И здесь

2021-11-16 14:57 UTC, Tenutes commented on src/hooks/use-auth.ts
> +  const isAuth = !!currentUser?.id || localStorage.getItem('isAuth') === 'true';
isAuth = Boolean(currentUser) || ...

2021-11-16 14:57 UTC, Tenutes commented on src/pages/Login/Login.tsx
>  import './Login.scss';
на это должен линтер ругаться. Это надо после всех импортов

2021-11-16 14:57 UTC, Tenutes commented on src/pages/Login/Login.tsx
> +    history.push('/');
А вот это лучше не делать. Вдруг человек хочет заново зайти. Кидай лучше на `logout`, чтоб оттуда уже на `login` обратно уходило

2021-11-16 14:57 UTC, Tenutes commented on src/pages/Main/Main.tsx
> +import './Main.scss';
И на это линтер должен ругаться, го перенесем.

2021-11-16 14:57 UTC, Tenutes commented on src/pages/Register/Register.tsx
> +    history.push('/');
Здесь аналогично странице логина

2021-11-16 14:57 UTC, Tenutes commented on src/store/slices/authSlice.ts
> +    resetCurrentUser(state) {
а точно ли нужен такой редьюсер, мб давай все переместим в `setCurrentUser`, просто дадим возможность ставить и null

2021-11-16 15:32 UTC, YurikEz commented on src/pages/Register/Register.tsx
> +    history.push('/');
Решил, есть нюанс описан выше на логине

2021-11-16 15:33 UTC, YurikEz commented on src/pages/Login/Login.tsx
> +    history.push('/');
Крч, если мы так сделаем, то при авторизации мы не успеем перейти на / и сразу полетит запрос на logout
Так что я добавил страницу logout и теперь по запросу /logout можно дополнительно разлогиниться
либо через ссылку в меню (да, вернул ссылку вместо кнопки, как и было)

2021-11-16 15:34 UTC, YurikEz commented on src/controllers/AuthController.ts
> +      .then(response => getData(response))
.then(response => getData(response))
нигде ниже править не буду, тк в другой таске все перепишу на RTK Query

2021-11-17 07:31 UTC, Tenutes approved these changes

2021-11-17 09:37 UTC, venmovs approved these changes

2021-11-17 16:47 UTC, spt30 requested changes

2021-11-17 16:47 UTC, spt30 commented on src/components/ui/Form/Form.tsx
> +// TODO: Переписать форму на Formik
переписать форму на react-hook-form 😄 
формик уже не модно

2021-11-17 16:47 UTC, spt30 commented on src/controllers/AuthController.ts
> +      .then(() => this.fetchUser())
.then(this.fetchUser)

2021-11-17 16:47 UTC, spt30 commented on src/hooks/redux-hooks.ts
> +export const useAppDispatch = () => useDispatch<AppDispatch>();
👍

2021-11-17 16:47 UTC, spt30 commented on src/hooks/use-auth.ts
> +  localStorage.setItem('isAuth', String(isAuth));
когда используешь такие штуки, всегда оборачивай их в if (typeof window !== 'undefined')
иначе когда придется прикрутить ssr, будешь бегать по проекту в панике и искать где что отвалилось

2021-11-17 16:47 UTC, spt30 commented on src/pages/Login/Login.tsx
> +    setForm({ ...form, [name]: value });
срочно переписать на react-hook-form 🤣 
никаких дата атрибутов в реакте!

2021-11-17 16:47 UTC, spt30 commented on src/pages/Login/Login.tsx
> +    setForm({ ...form, [name]: value });
шутки шутками, но дата-атрибуты и двусторонние биндинги — это совсем не react-way

2021-11-18 08:29 UTC, YurikEz commented on src/controllers/AuthController.ts
> +      .then(() => this.fetchUser())
На данном этапе это менять не буду
тк это ломает типизацию, а сами API и контроллеры мы планируем переписать на RTK Query

2021-11-18 15:26 UTC, YurikEz commented on src/components/ui/Form/Form.tsx
> +// TODO: Переписать форму на Formik
Ты меня уговорил
и я сделал

2021-11-18 15:36 UTC, Tenutes commented on package.json
> +    "@hookform/resolvers": "^2.8.3",
убирай шапочки

2021-11-18 15:42 UTC, Tenutes approved these changes

2021-11-18 15:50 UTC, venmovs approved these changes

2021-11-18 16:46 UTC, spt30 approved these changes
аж глаз радуется 👍

2021-11-18 16:46 UTC, spt30 commented on src/hooks/use-auth.ts
>    const isAuth = Boolean(currentUser) || localStorage.getItem('isAuth') === 'true';
тут бы тоже обернуть

2021-11-18 19:28 UTC, merged