add set Avatar
YaFriends/ya-game-frontend pull request #86
Opened 2021-11-28 19:17 UTC by YurikEz

Closes #83

2021-11-29 13:09 UTC, Tenutes requested changes

2021-11-29 13:09 UTC, Tenutes commented on src/pages/Profile/Profile.scss
> +        content: 'Изменить';
тааааакс, с этим надо что-то сделать, давай это будет в диве, который появляться будет (а лучше - кнопка), чтобы был перевод сразу

2021-11-29 13:09 UTC, Tenutes commented on src/pages/Profile/Profile.tsx
> +    currentUser && (
Это же уйдет потом? Выглядит странно

2021-11-29 13:09 UTC, Tenutes commented on src/pages/Profile/Profile.tsx
> +          <Settings url={url} userInfo={currentUser as UserData} />
Если без юзера венрнуть пустое что-то, то не придется кастовать

2021-11-29 13:44 UTC, YurikEz commented on src/pages/Profile/Profile.tsx
> +    currentUser && (
Надо что то придумать, тк в хуке еще нет пользователя, а он рисует компоненты
я думаю надо что то переделать в самом App.tsx

а так это помогает не рисовать компонент )

2021-11-29 13:45 UTC, YurikEz commented on src/pages/Profile/Profile.tsx
> +          <Settings url={url} userInfo={currentUser as UserData} />
Мы тут кастуем как я понимаю, потому что юзер мб null, а далее нам как бы null не нужен

2021-11-29 14:11 UTC, Tenutes commented on src/pages/Profile/Profile.tsx
> +          <Settings url={url} userInfo={currentUser as UserData} />
ну если выше ты сделать `if (!currentUser) {return <div> Загрузка </div>}`, к примеру, то кастовать не придется)

2021-11-29 16:40 UTC, venmovs approved these changes

2021-12-01 08:31 UTC, YurikEz commented on src/pages/Profile/Profile.tsx
> +    currentUser && (
 Убрал, сделал спинер выше

2021-12-01 08:32 UTC, YurikEz commented on src/pages/Profile/Profile.scss
> +        content: 'Изменить';
Тут уже в целом инпут, так что кнопка не нужна
добавлю появение спана по наведению

2021-12-01 08:57 UTC, Tenutes approved these changes

2021-12-01 09:05 UTC, merged