Прокинул данные пользователя в главное меню
YaFriends/ya-game-frontend pull request #89
Opened 2021-11-29 13:42 UTC by YurikEz

Closes #88

2021-11-29 14:14 UTC, Tenutes requested changes
Убрать консол логи и мержим! :)

2021-11-29 14:14 UTC, Tenutes commented on src/App.tsx
> +  console.log('isLoading', isLoading);
не очень хочется это видел в мастере)

2021-11-29 14:14 UTC, Tenutes commented on src/App.tsx
> +  console.log(isSuccess);
И это тоже

2021-11-29 14:14 UTC, Tenutes commented on src/App.tsx
> +  console.log(responseFetchUser);
И это

2021-11-29 16:35 UTC, venmovs approved these changes

2021-12-01 08:33 UTC, Tenutes approved these changes
!

2021-12-01 09:08 UTC, merged